# Generated by Django 5.0.4 on 2024-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='blogimag/'),
        ),
    ]
