# Generated by Django 5.0.4 on 2024-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('psw', models.CharField(max_length=50)),
                ('pswrepeat', models.CharField(max_length=50)),
            ],
        ),
    ]
